workflows:
  version: 2
  build:
    jobs:
      - node-latest

version: 2
jobs:
  node-latest:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
        keys:
          - yarn-packages-{{ checksum "yarn.lock" }}

      - run: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/workspace/node_modules
            - ~/.cache/yarn/
      - run: yarn test
      - store_artifacts:
          path: coverage
      - run: ts-node src/cli.ts --circleci-workflow=node-multi-build
